# This is the main config file for the budget

vars:
  # Number of teams in SR2012
  teams: 24

  # Number of those teams that will be mentored by Bristol students
  bristol_teams: 3

  # Number of students in SR2012
  students: 6 * teams

  # Number of dev kits we'll own in SR2012
  dev_kits: 8

  # Total number of kits we'll own in SR2012
  total_kits: ceiling(teams * 1.25) + dev_kits

  # Number of whole kits that were completely lost/destroyed in SR2013
  sr2012_destroyed_kits: 2

  #########################################################
  # The following variables all refer to SR2013,
  # kit will need to be manufactured in SR2012.

  # Number of teams in SR2013
  sr2013_teams: floor(1.5 * teams)

  # Number of dev kits we'll own in SR2013
  sr2013_dev_kits: dev_kits + 5

  # Total number of kits we'll own in SR2013
  sr2013_total_kits: ceiling(sr2013_teams * 1.25) + sr2013_dev_kits

  # Number of kits to manufacture in SR2013
  new_kits: sr2013_total_kits - total_kits + sr2012_destroyed_kits

  # Number of kits there will be at the end of SR2013
  sr2013_end_kits: sr2013_total_kits

  ############################################################
  # The following all refer to SR2014

  # Number of teams in SR2014
  sr2014_teams: floor(1.5 * sr2013_teams)

  # Number of dev kits we'll own in SR2014
  sr2014_dev_kits: sr2013_dev_kits + 5

  # Total number of kits we'll own in SR2014
  sr2014_total_kits: ceiling(sr2014_teams * 1.25) + sr2013_dev_kits

  # Number of kits to manufacture in SR2014
  sr2014_new_kits: sr2014_total_kits - sr2013_end_kits

  # Number of kits there will be at the end of SR2014
  sr2014_end_kits: sr2014_total_kits

  ############################################################
  # The following all refer to SR2015

  # Number of teams in SR2015
  sr2015_teams: floor(1.0 * sr2014_teams)

  # Number of dev kits we'll own in SR2015
  sr2015_dev_kits: sr2014_dev_kits + 5

  # Total number of kits we'll own in SR2015
  sr2015_total_kits: ceiling(sr2015_teams * 1.125) + sr2015_dev_kits

  # Number of kits to manufacture in SR2015
  sr2015_new_kits: sr2015_total_kits - sr2014_end_kits
